// @generated by @matari/mui. DO NOT EDIT BY HAND.
pub fn generated_scene() -> mui_core::SceneSpec {
    let root = mui_layout::Node::row(
        "",
        vec![
            mui_layout::Node::leaf(
                "tab\u{1}\u{8}\u{c}\\\"שלום🎹",
                mui_layout::Size::new(80f64, 32f64),
            ),
            mui_layout::Node::leaf("panel", mui_layout::Size::new(320f64, 100f64)),
        ],
    )
    .gap(mui_core::Spacing::m())
    .padding(mui_core::Spacing::s())
    .axis(mui_layout::Axis::Column)
    .width(mui_layout::Sizing::Fill)
    .height(mui_layout::Sizing::Hug);
    let theme = mui_core::Theme {
        mode: mui_core::Mode::Light,
        palette: mui_core::Palette {
            light: mui_core::Seeds {
                primary: [
                    mui_core::Rgb::new(170, 34, 204),
                    mui_core::Rgb::new(68, 204, 170),
                    mui_core::Rgb::new(221, 85, 34),
                ],
                neutral: mui_core::Rgb::new(136, 136, 136),
                ..mui_core::Seeds::default()
            },
            dark: Some(mui_core::Seeds {
                primary: [
                    mui_core::Rgb::new(136, 85, 255),
                    mui_core::Rgb::new(68, 187, 170),
                    mui_core::Rgb::new(255, 136, 68),
                ],
                neutral: mui_core::Rgb::new(119, 119, 119),
                ..mui_core::Seeds {
                    primary: [
                        mui_core::Rgb::new(170, 34, 204),
                        mui_core::Rgb::new(68, 204, 170),
                        mui_core::Rgb::new(221, 85, 34),
                    ],
                    neutral: mui_core::Rgb::new(136, 136, 136),
                    ..mui_core::Seeds::default()
                }
            }),
        },
        corners: mui_core::CornerProfile::new(1e+21f64, 1e-7f64),
        spacing: mui_core::SpacingScale {
            xs: 4f64,
            s: 8f64,
            m: 12f64,
            l: 18f64,
            xl: 28f64,
        },
        stroke_width: -0f64,
    };
    mui_core::SceneSpec::new(root)
        .theme(theme)
        .available_width(336f64)
        .surface(
            mui_core::SurfaceSpec::frame("tab", "tab\u{1}\u{8}\u{c}\\\"שלום🎹")
                .radius(mui_core::FrameRadius::Global)
                .extend_to(mui_core::Edge::Bottom, "panel"),
        )
        .surface(
            mui_core::SurfaceSpec::frame("panel", "panel").radius(mui_core::FrameRadius::Global),
        )
        .surface(
            mui_core::SurfaceSpec::merge("shell", ["tab", "panel"])
                .corners(mui_core::CornerRule::Global),
        )
}
