// @generated by @matari/mui. DO NOT EDIT BY HAND.
pub fn generated_scene() -> mui_core::SceneSpec {
    let root = mui_layout::column(vec![
        mui_layout::column(vec![mui_layout::column(vec![mui_layout::column(vec![
            mui_layout::leaf(28.0, 28.0).id("plus"),
            mui_layout::leaf(28.0, 28.0).id("pie-a"),
            mui_layout::leaf(28.0, 28.0).id("pie-b"),
        ])
        .gap(10.0)
        .align(mui_layout::Align::Center)])
        .padding(10.0)
        .align(mui_layout::Align::Center)])
        .id("tab")
        .padding(12.0)
        .min_size(mui_layout::Size::new(92.0, 0.0))
        .align(mui_layout::Align::Center),
        mui_layout::leaf(520.0, 230.0).id("panel"),
    ])
    .id("root")
    .gap(0.0)
    .align(mui_layout::Align::Start)
    .justify(mui_layout::Justify::Start);
    let theme = mui_core::Theme {
        corners: mui_core::CornerProfile::new(28.0, 32.0),
        spacing: mui_core::SpacingScale {
            xs: 4.0,
            s: 8.0,
            m: 12.0,
            l: 18.0,
            xl: 28.0,
        },
        palette: mui_core::Palette {
            primary: mui_core::Pigment::new(242.0, 0.131),
            step: 0.045,
            hover: 0.11,
            ..mui_core::Palette::NEUTRAL
        },
        stroke_width: 1.5,
    };
    mui_core::SceneSpec::new(root)
        .theme(theme)
        .surface(mui_core::SurfaceSpec::frame("panel").radius(mui_core::Radius::Global))
        .surface(mui_core::SurfaceSpec::frame("tab").radius(mui_core::Radius::Global))
        .surface(
            mui_core::SurfaceSpec::merge("outer", ["panel", "tab"])
                .corners(mui_core::CornerRule::Global),
        )
        .surface(mui_core::SurfaceSpec::inset(
            "pill-shell",
            "tab",
            mui_core::Spacing::px(12.0),
        ))
}
