// @generated by @matari/mui. DO NOT EDIT BY HAND.
pub fn generated_ui() -> Result<mui_core::Ui, mui_core::SceneError> {
    let theme = mui_core::Theme {
        ..Default::default()
    };
    Ok(mui_core::item("")
        .layout(mui_layout::Flow::Column)
        .round(mui_core::Rounding::separate(
            mui_core::Spacing::m(),
            mui_core::Spacing::s(),
        ))
        .gap(mui_core::Spacing::m())
        .width(mui_layout::Sizing::Fill)
        .height(mui_layout::Sizing::Hug)
        .merge(["filter", "panel"])
        .children([
            mui_core::item("")
                .layout(mui_layout::Flow::Row)
                .gap(mui_core::Spacing::s())
                .pad(mui_core::Spacing::m())
                .width(mui_layout::Sizing::Fill)
                .position(mui_layout::Horizontal::Center, mui_layout::Vertical::Middle)
                .children([
                    mui_core::item("osc")
                        .text("Oscillator")
                        .on_tap("select-osc")
                        .pad(mui_core::Spacing::s()),
                    mui_core::item("filter")
                        .text("Filter")
                        .on_tap("select-filter")
                        .extend_to("panel")
                        .color(mui_core::Color::Raised)
                        .pad(mui_core::Spacing::s()),
                    mui_core::item("fx")
                        .text("Effects")
                        .on_tap("select-fx")
                        .pad(mui_core::Spacing::s()),
                ]),
            mui_core::item("panel")
                .layout(mui_layout::Flow::Grid(3))
                .gap(mui_core::Spacing::m())
                .pad(mui_core::Spacing::l())
                .width(mui_layout::Sizing::Fill)
                .children([
                    mui_core::item("cutoff").width(64f64).height(64f64),
                    mui_core::item("resonance").width(64f64).height(64f64),
                    mui_core::item("drive").width(64f64).height(64f64),
                ]),
        ])
        .build_with(theme)?
        .available_width(360f64))
}
