// @generated by @matari/mui. DO NOT EDIT BY HAND.
pub fn generated_scene() -> mui_core::SceneSpec {
    let root = mui_layout::Node::column(
        "root",
        vec![
            mui_layout::Node::column(
                "tab-frame",
                vec![mui_layout::Node::column(
                    "pill-frame",
                    vec![mui_layout::Node::column(
                        "controls",
                        vec![
                            mui_layout::Node::leaf("plus", mui_layout::Size::new(28f64, 28f64)),
                            mui_layout::Node::leaf("pie-a", mui_layout::Size::new(28f64, 28f64)),
                            mui_layout::Node::leaf("pie-b", mui_layout::Size::new(28f64, 28f64)),
                        ],
                    )
                    .gap(10f64)
                    .align(mui_layout::Align::Center)],
                )
                .padding(10f64)
                .align(mui_layout::Align::Center)],
            )
            .padding(12f64)
            .min_size(mui_layout::Size::new(92f64, 0f64))
            .align(mui_layout::Align::Center),
            mui_layout::Node::leaf("panel-frame", mui_layout::Size::new(520f64, 230f64)),
        ],
    )
    .gap(0f64)
    .align(mui_layout::Align::Start)
    .justify(mui_layout::Justify::Start);
    let theme = mui_core::Theme {
        corners: mui_core::CornerProfile::new(28f64, 32f64),
        spacing: mui_core::SpacingScale {
            xs: 4f64,
            s: 8f64,
            m: 12f64,
            l: 18f64,
            xl: 28f64,
        },
        stroke_width: 1.5f64,
        ..Default::default()
    };
    mui_core::SceneSpec::new(root)
        .theme(theme)
        .surface(
            mui_core::SurfaceSpec::frame("panel", "panel-frame")
                .radius(mui_core::FrameRadius::Global),
        )
        .surface(
            mui_core::SurfaceSpec::frame("tab", "tab-frame").radius(mui_core::FrameRadius::Global),
        )
        .surface(
            mui_core::SurfaceSpec::merge("outer", ["panel", "tab"])
                .corners(mui_core::CornerRule::Global),
        )
        .surface(mui_core::SurfaceSpec::inset(
            "pill-shell",
            "tab",
            mui_core::Spacing::px(12f64),
        ))
}
