// @generated by @matari/mui. DO NOT EDIT BY HAND.
pub fn generated_scene() -> mui_core::SceneSpec {
    let root = mui_layout::Node::column(
        "root",
        vec![
            mui_layout::Node::column(
                "tab-frame",
                vec![mui_layout::Node::column(
                    "pill-frame",
                    vec![mui_layout::Node::column(
                        "controls",
                        vec![
                            mui_layout::Node::leaf("plus", mui_layout::Size::new(28.0, 28.0)),
                            mui_layout::Node::leaf("pie-a", mui_layout::Size::new(28.0, 28.0)),
                            mui_layout::Node::leaf("pie-b", mui_layout::Size::new(28.0, 28.0)),
                        ],
                    )
                    .gap(10.0)
                    .align(mui_layout::Align::Center)],
                )
                .padding(10.0)
                .align(mui_layout::Align::Center)],
            )
            .padding(12.0)
            .min_size(mui_layout::Size::new(92.0, 0.0))
            .align(mui_layout::Align::Center),
            mui_layout::Node::leaf("panel-frame", mui_layout::Size::new(520.0, 230.0)),
        ],
    )
    .gap(0.0)
    .align(mui_layout::Align::Start)
    .justify(mui_layout::Justify::Start);
    let theme = mui_core::Theme {
        corners: mui_core::CornerProfile::new(28.0, 32.0),
        spacing: mui_core::SpacingScale {
            xs: 4.0,
            s: 8.0,
            m: 12.0,
            l: 18.0,
            xl: 28.0,
        },
        stroke_width: 1.5,
    };
    mui_core::SceneSpec::new(root)
        .theme(theme)
        .surface(
            mui_core::SurfaceSpec::frame("panel", "panel-frame")
                .radius(mui_core::FrameRadius::Global),
        )
        .surface(
            mui_core::SurfaceSpec::frame("tab", "tab-frame").radius(mui_core::FrameRadius::Global),
        )
        .surface(
            mui_core::SurfaceSpec::merge("outer", ["panel", "tab"])
                .corners(mui_core::CornerRule::Global),
        )
        .surface(mui_core::SurfaceSpec::inset(
            "pill-shell",
            "tab",
            mui_core::Spacing::px(12.0),
        ))
}
