[package]
name = "mui-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mui-geometry = { path = "../mui-geometry" }
mui-style = { path = "../mui-style" }
mui-layout = { path = "../mui-layout" }
mui-text = { path = "../mui-text" }

[dev-dependencies]
epaint_default_fonts = "0.36"
