[package]
name = "mui-motion-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mui.workspace = true
base64 = "0.22"
sha2 = "0.10"
mui-scene.workspace = true
mui-vello = { workspace = true, features = ["cpu"] }
serde_json.workspace = true
png.workspace = true

[dev-dependencies]
epaint_default_fonts.workspace = true

[lints]
workspace = true
