[package]
name = "mui-playground"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mui-scene.workspace = true
mui-material.workspace = true
mui-symbols.workspace = true
mui-text.workspace = true
mui-vello = { workspace = true, features = ["cpu"] }
vello_cpu.workspace = true
syn = { version = "2", features = ["full", "parsing"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
wasm-bindgen = "0.2.128"
epaint_default_fonts.workspace = true

[lints]
workspace = true
