[package]
name = "mui"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
text = ["dep:mui-text"]
system-fonts = ["text", "mui-core/system-fonts"]
egui = ["dep:mui-egui"]

[dependencies]
mui-text = { path = "../mui-text", optional = true }
mui-core = { path = "../mui-core" }
mui-layout = { path = "../mui-layout" }
mui-geometry = { path = "../mui-geometry" }
mui-tessellate = { path = "../mui-tessellate" }
mui-egui = { path = "../mui-egui", optional = true }
