[package]
name = "mui"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
text = ["dep:mui-text"]
system-fonts = ["text", "mui-core/system-fonts"]
egui = ["dep:mui-egui"]
vello = ["dep:mui-vello"]
cpu = ["vello", "mui-vello/cpu"]
gpu = ["vello", "mui-vello/gpu"]

[dependencies]
mui-text = { path = "../mui-text", optional = true }
mui-core = { path = "../mui-core" }
mui-layout = { path = "../mui-layout" }
mui-geometry = { path = "../mui-geometry" }
mui-tessellate = { path = "../mui-tessellate" }
mui-input = { path = "../mui-input" }
mui-vello = { path = "../mui-vello", optional = true, default-features = false }
mui-egui = { path = "../mui-egui", optional = true }

[dev-dependencies]
epaint_default_fonts = "0.36"
