// Build-time TS -> typed Rust builders. No JavaScript runtime is required in the plugin.
// @ts-ignore - keep this package dependency-free; Node provides these modules.
import { writeFile } from "node:fs/promises";
// @ts-ignore
import { pathToFileURL } from "node:url";
import type { Align, CornerRule, Radius, Insets, Justify, Node, Oklch, Palette, Scene, Spacing, Surface } from "./index.js";

declare const process: { argv: string[] };

const q = (s: string) => JSON.stringify(s);
const n = (v: number) => {
  if (!Number.isFinite(v)) throw new Error(`non-finite number: ${v}`);
  return Number.isInteger(v) ? `${v}.0` : String(v);
};
const align = (a?: Align) => a ? `mui_layout::Align::${({start:"Start",center:"Center",end:"End",stretch:"Stretch"} as const)[a]}` : null;
const justify = (j?: Justify) => j ? `mui_layout::Justify::${({start:"Start",center:"Center",end:"End","space-between":"SpaceBetween"} as const)[j]}` : null;

function insets(v: Insets): string {
  if (typeof v === "number") return `.padding(${n(v)})`;
  return `.insets(mui_layout::Insets { left: ${n(v.left)}, right: ${n(v.right)}, top: ${n(v.top)}, bottom: ${n(v.bottom)} })`;
}
function decorate(base: string, p: Node["props"]): string {
  let s = base;
  if (p.id !== undefined) s += `.id(${q(p.id)})`;
  if (p.gap !== undefined) s += `.gap(${n(p.gap)})`;
  if (p.padding !== undefined) s += insets(p.padding);
  if (p.min) s += `.min_size(mui_layout::Size::new(${n(p.min[0])}, ${n(p.min[1])}))`;
  if (p.max) s += `.max_size(mui_layout::Size::new(${n(p.max[0])}, ${n(p.max[1])}))`;
  if (p.grow !== undefined) s += `.grow(${n(p.grow)})`;
  const a = align(p.align); if (a) s += `.align(${a})`;
  const j = justify(p.justify); if (j) s += `.justify(${j})`;
  return s;
}
function node(v: Node, depth = 1): string {
  const pad = "    ".repeat(depth);
  if (v.kind === "leaf") return decorate(`mui_layout::leaf(${n(v.size[0])}, ${n(v.size[1])})`, v.props);
  const children = v.children.map(c => `${pad}    ${node(c, depth + 1)}`).join(",\n");
  return decorate(`mui_layout::${v.kind}(vec![\n${children}\n${pad}])`, v.props);
}
function spacing(v: Spacing): string {
  return v.kind === "px" ? `mui_core::Spacing::px(${n(v.value)})` : `mui_core::Spacing::${v.value}()`;
}
function radius(v: Radius): string {
  switch (v.kind) {
    case "global": return `mui_core::Radius::Global`;
    case "absolute": return `mui_core::Radius::Absolute(${n(v.value)})`;
    case "parent-normalized": return `mui_core::Radius::ParentNormalized { parent: ${q(v.parent)}.into(), scale: ${n(v.scale)} }`;
  }
}
function cornerRule(v: CornerRule): string {
  switch (v.kind) {
    case "global": return `mui_core::CornerRule::Global`;
    case "absolute": return `mui_core::CornerRule::Absolute(mui_core::CornerProfile::new(${n(v.convex)}, ${n(v.concave)}))`;
    case "global-scaled": return `mui_core::CornerRule::GlobalScaled(${n(v.scale)})`;
  }
}
function surface(v: Surface): string {
  switch (v.kind) {
    case "frame": return `mui_core::SurfaceSpec::frame(${q(v.id)}).radius(${radius(v.radius)})`;
    case "merge": return `mui_core::SurfaceSpec::merge(${q(v.id)}, [${v.inputs.map(q).join(", ")}]).corners(${cornerRule(v.corners)})`;
    case "inset": return `mui_core::SurfaceSpec::inset(${q(v.id)}, ${q(v.parent)}, ${spacing(v.distance)})`;
    case "outset": return `mui_core::SurfaceSpec::outset(${q(v.id)}, ${q(v.parent)}, ${spacing(v.distance)})`;
  }
}
/// Unstated fields fall through to `Palette::DARK` rather than being restated
/// here, so the two sides cannot drift.
function palette(p: Palette): string {
  const c = (v: Oklch) => v.length === 4
    ? `mui_core::Color::oklcha(${v.map(n).join(", ")})`
    : `mui_core::Color::oklch(${v.map(n).join(", ")})`;
  const fields: string[] = [];
  for (const k of ["surface", "accent", "ink", "error"] as const) {
    const v = p[k];
    if (v) fields.push(`${k}: ${c(v)}`);
  }
  for (const k of ["step", "hover"] as const) {
    const v = p[k];
    if (v !== undefined) fields.push(`${k}: ${n(v)}`);
  }
  return `mui_core::Palette { ${fields.join(", ")}${fields.length ? ", " : ""}..mui_core::Palette::DARK }`;
}

function compile(scene: Scene): string {
  const t = scene.theme ?? {};
  const c = t.corners ?? { convex: 18, concave: 14 };
  const sp = { xs:4, s:8, m:12, l:18, xl:28, ...(t.spacing ?? {}) };
  let out = `// @generated by @matari/mui. DO NOT EDIT BY HAND.\n`;
  out += `pub fn generated_scene() -> mui_core::SceneSpec {\n`;
  out += `    let root = ${node(scene.root, 1)};\n`;
  out += `    let theme = mui_core::Theme {\n`;
  out += `        corners: mui_core::CornerProfile::new(${n(c.convex)}, ${n(c.concave)}),\n`;
  out += `        spacing: mui_core::SpacingScale { xs: ${n(sp.xs)}, s: ${n(sp.s)}, m: ${n(sp.m)}, l: ${n(sp.l)}, xl: ${n(sp.xl)} },\n`;
  if (t.palette) out += `        palette: ${palette(t.palette)},\n`;
  out += `        stroke_width: ${n(t.strokeWidth ?? 1.5)},\n    };\n`;
  out += `    mui_core::SceneSpec::new(root).theme(theme)`;
  if (scene.offered) out += `.offered(mui_layout::Size::new(${n(scene.offered[0])}, ${n(scene.offered[1])}))`;
  for (const s of scene.surfaces) out += `\n        .surface(${surface(s)})`;
  out += `\n}\n`;
  return out;
}

const [, , input, output] = process.argv;
if (!input || !output) throw new Error("usage: compiler.js <scene.js> <output.rs>");
const mod = await import(pathToFileURL(input).href);
const scene = mod.default as Scene;
await writeFile(output, compile(scene), "utf8");
