// Generate cross-language checks. Run from any directory; output is deterministic.
import {sources} from './vectors_fixture.mjs';
import {defaults,field,pixel,rgba8} from './engine.mjs';
import fs from 'node:fs';
const f=x=>Number.isInteger(x)?`${x}.0`:`${x}`;
let rows=[];
for(const progress of [0,.25,.5,.75,1]) for(const [x,y]of [[-1,12],[0,12],[12,12],[23.5,12],[25,12],[36,2],[51,12]]) {
 const o={...defaults(),progress},v=field(sources(),x,y,o),c=rgba8(pixel(sources(),x,y,o));
 rows.push(`        (${f(progress)}, ${f(x)}, ${f(y)}, ${f(v.distance)}, ${f(v.weights[0])}, [${c.join(', ')}]),`);
}
const rust=`// Generated by tools/material-weld-demo/generate_vectors.mjs.\n// Expected values came from the tested JS reference, not an executed Rust build.\n#[test]\nfn javascript_reference_vectors_match_the_rust_kernel() {\n    let r = request();\n    let cases: &[(f64, f64, f64, f64, f64, [u8; 4])] = &[\n${rows.join('\n')}\n    ];\n    for &(t, x, y, expected_d, expected_w, expected_rgba) in cases {\n        let weld = r.weld.morph(t);\n        let at = Point::new(x, y);\n        let sample = sample_field(&r.sources, at, weld).unwrap();\n        close(sample.distance, expected_d);\n        close(sample.weights()[0], expected_w);\n        let rgba = pixel(&r.sources, at, weld, 1.0).rgba8();\n        for j in 0..4 {\n            assert!((i16::from(rgba[j])-i16::from(expected_rgba[j])).abs() <= 1);\n        }\n    }\n}\n`;
if(process.argv[2])fs.writeFileSync(process.argv[2],rust);else process.stdout.write(rust);
