import assert from 'node:assert/strict';
import {unproject} from './input.mjs';
const quad=[{x:20,y:30},{x:240,y:55},{x:210,y:170},{x:0,y:140}];
for(let i=0;i<4;i++){const p=unproject(quad,quad[i].x,quad[i].y,100,80);assert(Math.abs(p.x-[0,100,100,0][i])<1e-6);assert(Math.abs(p.y-[0,0,80,80][i])<1e-6);}
const {default:puppeteer}=await import(process.env.PUPPETEER_MODULE||'puppeteer-core');
const browser=await puppeteer.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});
try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width:1440,height:1050});await page.goto(process.argv[2]||'http://localhost:3022');await page.click('#connect');await page.waitForFunction(()=>!!window.muiLive,{timeout:30000});
 const send=c=>page.evaluate(c=>window.muiLive.send(c),c),wait=ms=>new Promise(r=>setTimeout(r,ms));
 await page.click('#record');await page.waitForFunction(()=>document.querySelector('#record').textContent==='Stop recording');await send({op:'note_on',note:69,velocity:96});await page.waitForFunction(()=>window.muiAudioPeak>.003);
 const initial=await page.evaluate(()=>({revision:window.muiLive.state.revision,telemetry:JSON.stringify(window.muiLive.state.telemetry),sources:[...document.querySelectorAll('.mui-plane img')].map(i=>i.src)}));await wait(650);
 const next=await page.evaluate(()=>({revision:window.muiLive.state.revision,telemetry:JSON.stringify(window.muiLive.state.telemetry),sources:[...document.querySelectorAll('.mui-plane img')].map(i=>i.src)}));assert(next.revision>initial.revision+3,'continuous editor ticks');assert.notEqual(next.telemetry,initial.telemetry,'engine telemetry moves');assert.notDeepEqual(next.sources,initial.sources,'native visual pixels move without edits');
 await page.evaluate(async()=>{const ids=window.muiMotion.components.map(s=>s.id);await window.muiMotion.select(ids.includes('voice')?['voice']:['osc/0','mod/1']);});
 for(const [id,value]of [['explode',65],['angle',-20],['stretch',130]])await page.$eval('#'+id,(el,v)=>{el.value=v;el.dispatchEvent(new Event('input'));},String(value));
 // Place a marker at the actual native control coordinate. Its projected
 // browser point must invert through the same transformed plane on input.
 const control=await page.evaluate(()=>{const state=window.muiLive.state;const s=state.scene.surfaces.find(s=>s.id==='gain')||state.scene.surfaces.find(s=>/osc\/0.*level/.test(s.id));if(!s)return null;const group=s.id==='gain'?'voice':'osc/0';const planes=[...document.querySelectorAll('.mui-plane')].filter(p=>p.dataset.muiId===group);const plane=planes.find(p=>{const x=parseFloat(p.style.left),y=parseFloat(p.style.top);return s.frame[0]>=x&&s.frame[1]>=y&&s.frame[0]<x+parseFloat(p.style.width)&&s.frame[1]<y+parseFloat(p.style.height);});if(!plane)return null;const marker=document.createElement('span');Object.assign(marker.style,{position:'absolute',width:0,height:0,left:(s.frame[0]+s.frame[2]/2-parseFloat(plane.style.left))+'px',top:(s.frame[1]+s.frame[3]/2-parseFloat(plane.style.top))+'px',pointerEvents:'none'});plane.append(marker);const r=marker.getBoundingClientRect();marker.remove();return{x:r.x,y:r.y,value:state.modules[0].parameters.find(p=>p.id==='level').value,id:s.id};});
 assert(control,'native level surface exists');await page.mouse.move(control.x,control.y);await page.mouse.down();await page.mouse.move(control.x,control.y-45,{steps:12});await wait(150);await page.mouse.up();await page.waitForFunction(old=>window.muiLive.state.modules[0].parameters.find(p=>p.id==='level').value!==old,{timeout:10000},control.value);
 await send({op:'set',id:await page.evaluate(()=>window.muiLive.state.modules[0].id),field:'level',value:.3});await page.waitForFunction(()=>Math.abs(window.muiLive.state.modules[0].parameters.find(p=>p.id==='level').value-.3)<.001);
 await page.evaluate(async()=>{const m=window.muiMotion;const id=m.components.some(s=>s.id==='voice')?'voice':'osc/0';await m.highlight(id);await m.animate(id,{scaleX:1.1,scaleY:1.1,z:160},.25);if(id==='voice'){const before=m.components.find(s=>s.id==='gain').frame.slice(2);await m.resize(id,540,340);const knob=m.components.find(s=>s.id==='gain');if(knob.frame[2]!==before[0]||knob.frame[3]!==before[1])throw Error('Native reflow stretched the knob');}await m.focus(id);});
 await page.evaluate(async()=>{const m=window.muiMotion;if(m.components.some(s=>s.id==='mod/1')){await m.focus('mod/1');await m.perform([{wait:1.5},{animate:{id:'mod/1',to:{scaleX:1,scaleY:1,z:180},seconds:1}},{wait:1}]);await m.select(['osc/0','mod/1']);m.explode(.65);await new Promise(r=>setTimeout(r,800));}});
 await page.screenshot({path:'/tmp/mui-motion-interactive.png'});
 for(const note of [71,72]){await send({op:'panic'});await send({op:'note_on',note});await wait(450);}await send({op:'panic'});await page.click('#record');await page.waitForFunction(()=>!!window.muiLastRecording,{timeout:30000});const take=await page.evaluate(()=>window.muiLastRecording);console.log(JSON.stringify(take));
 const health=await page.evaluate(()=>window.muiAudioHealth);assert.equal(health.dropped,0);assert.deepEqual(errors,[]);console.log('PASS continuous DSP-driven pixels, detached native knob input, recording, audio',health);await page.close();
 const film=await browser.newPage();await film.goto(new URL(take.url,process.argv[2]||'http://localhost:3022').href);await film.waitForFunction(()=>!!window.__timelines?.['mui-performance'],{timeout:60000});const seek=t=>film.evaluate(t=>{window.__timelines['mui-performance'].seek(t,false);return [...document.querySelectorAll('.mui-plane img')].map(i=>i.src);},t);const a=await seek(.5);assert.notDeepEqual(await seek(1.1),a);await seek(take.seconds-.1);assert.deepEqual(await seek(.5),a);console.log('PASS recorded native animation changes and seeks deterministically');
}finally{await browser.close()}
